[build]
  command = "npm run build"
  publish = ".next"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[build.environment]
  NEXT_PUBLIC_API_URL = "https://profitedgeeedge.netlify.app"
  NEXT_TELEMETRY_DISABLED = "1"
