[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://profitedgeeedge.netlify.app"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/api/*"  # this matches any route starting with /api/
  to = "/.netlify/functions/nextjs-server/api/:splat"  # this is the path to the API handler
  status = 200
  force = true

[functions]
  # This will create the API as a Netlify Function
  external_node_modules = ["@netlify/plugin-nextjs"]
  included_files = [".env*"]
  node_bundler = "esbuild"
