[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force Next.js runtime
[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_EDGE_RUNTIME = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next-api/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions"]
